### ISSUE TITLE
Replace DEFAULT_FILE_STORAGE with STORAGES 

### ISSUE THREAD

**Issue by awais786** [openedx/public-engineering#369]
**Django 4.2** introduced the **STORAGES** setting, a modern and more flexible mechanism for configuring multiple storage backends. As of Django 5.2, **DEFAULT_FILE_STORAGE** and **STORAGES** are mutually exclusive, and using both simultaneously will raise an ImproperlyConfigured error.

**Goal**
Remove the legacy **DEFAULT_FILE_STORAGE** setting from `openedx` and migrate to the **STORAGES** dictionary-based configuration.

**Current Approach**
For compatibility with Django 5.2, we're currently loading storage classes using: 
`from django.utils.module_loading import import_string`

But if future we should use the storages.

**sample setting** 
```
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "profile_images": {
        "BACKEND": "openedx.core.storage.OverwriteStorage",
        "OPTIONS": {
            "location": os.path.join(MEDIA_ROOT, "profile-images/"),
            "base_url": os.path.join(MEDIA_URL, "profile-images/"),
        },
    },
    "course_metadata_export": {
        "BACKEND": "openedx.core.storage.OverwriteStorage",
        "OPTIONS": {
            "location": os.path.join(MEDIA_ROOT, "courses-export/"),
            "base_url": os.path.join(MEDIA_URL, "courses-export/"),
        },
    },
}
```

Django useful PR https://github.com/django/django/pull/15610

**Comment by awais786** [comment]
@dwong2708 another ticket in pipeline. Again it will contains sub-tickets for each PR.

**Comment by awais786** [comment]
1: We need to make sure existing configurations ( ymls ) works with latest code. Because different settings are using different parameters e.g 

```
PROFILE_IMAGE_BACKEND:
  class: storages.backends.s3boto3.S3Boto3Storage
  options:
    bucket_name: profile-images
    custom_domain: 12345.cloudfront.net
    default_acl: public-read
    location: LINTING
    object_parameters:
      CacheControl: max-age-31536000
```
But apparently new storages dict needs some thing like this 

```
"profile_images": {
        "BACKEND": "openedx.core.storage.OverwriteStorage",
        "OPTIONS": {
            "location": os.path.join(MEDIA_ROOT, "profile-images/"),
            "base_url": os.path.join(MEDIA_URL, "profile-images/"),
        },
    },
```

So it requires some discovery.
